### ISSUE TITLE
CORS 관련 문제

### ISSUE THREAD

**Issue by jk960903** [HyeongJun94/backSwim#16]
# 이슈 내용

CORS 에러 발생

# 상세 내용 

CORS : Cross - Origin - Resource - Sharing 

CORS 문제는 실행중인 웹 애플리케이션에서 다른 출처의 자원에 접근 할 때 발생합니다. 

웹 애플리케이션의 리소스가 자신의 출처(도메인 , 프로토콜 , 포트)등이 다를 때 교차 출처 HTTP 요청을 실행하게 되는데

이의 보안상의 이유 때문에 발생하게 되었습니다. 

서버 API 사용 관련하여 외부에서 API 호출시 CORS 오류가 발생한다는 것을 인지하여 긴급 픽스 들어갔습니다.

**Comment by HyeongJun94** [comment]
#17 에서 의논합니다
