### ISSUE TITLE
resend 이메일 , 구현때 사용할 유저 삭제 부재

### ISSUE THREAD

**Issue by jk960903** [HyeongJun94/backSwim#40]
이메일이 정상 발송되지 않았을때 혹은 너무 오래 인증하지 않아 보이지 않는 이메일 혹은 인증날짜가 지나 다시 보낼수 있는 resend 이메일  API 부재 

구현때 사용할 유저 삭제 부재

**Comment by HyeongJun94** [comment]
#41 에서 끝났습니다
